/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from "@solana/kit";
import { getKeyDecoder, getKeyEncoder, type Key, type KeyArgs } from "../types";

export type GlobalState = {
  key: Key;
  admin: Address;
  protocolFeeRecipient: Address;
  tokenMint: Address;
  owedProtocolFee: bigint;
  bpsFee: number;
  protocolFeeBpsOfBps: number;
  paused: boolean;
  oracleCount: number;
  bump: number;
};

export type GlobalStateArgs = {
  key: KeyArgs;
  admin: Address;
  protocolFeeRecipient: Address;
  tokenMint: Address;
  owedProtocolFee: number | bigint;
  bpsFee: number;
  protocolFeeBpsOfBps: number;
  paused: boolean;
  oracleCount: number;
  bump: number;
};

/** Gets the encoder for {@link GlobalStateArgs} account data. */
export function getGlobalStateEncoder(): FixedSizeEncoder<GlobalStateArgs> {
  return getStructEncoder([
    ["key", getKeyEncoder()],
    ["admin", getAddressEncoder()],
    ["protocolFeeRecipient", getAddressEncoder()],
    ["tokenMint", getAddressEncoder()],
    ["owedProtocolFee", getU64Encoder()],
    ["bpsFee", getU16Encoder()],
    ["protocolFeeBpsOfBps", getU16Encoder()],
    ["paused", getBooleanEncoder()],
    ["oracleCount", getU8Encoder()],
    ["bump", getU8Encoder()],
  ]);
}

/** Gets the decoder for {@link GlobalState} account data. */
export function getGlobalStateDecoder(): FixedSizeDecoder<GlobalState> {
  return getStructDecoder([
    ["key", getKeyDecoder()],
    ["admin", getAddressDecoder()],
    ["protocolFeeRecipient", getAddressDecoder()],
    ["tokenMint", getAddressDecoder()],
    ["owedProtocolFee", getU64Decoder()],
    ["bpsFee", getU16Decoder()],
    ["protocolFeeBpsOfBps", getU16Decoder()],
    ["paused", getBooleanDecoder()],
    ["oracleCount", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link GlobalState} account data. */
export function getGlobalStateCodec(): FixedSizeCodec<
  GlobalStateArgs,
  GlobalState
> {
  return combineCodec(getGlobalStateEncoder(), getGlobalStateDecoder());
}

export function decodeGlobalState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<GlobalState, TAddress>;
export function decodeGlobalState<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<GlobalState, TAddress>;
export function decodeGlobalState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<GlobalState, TAddress> | MaybeAccount<GlobalState, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getGlobalStateDecoder(),
  );
}

export async function fetchGlobalState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<GlobalState, TAddress>> {
  const maybeAccount = await fetchMaybeGlobalState(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeGlobalState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<GlobalState, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeGlobalState(maybeAccount);
}

export async function fetchAllGlobalState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<GlobalState>[]> {
  const maybeAccounts = await fetchAllMaybeGlobalState(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeGlobalState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<GlobalState>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeGlobalState(maybeAccount));
}

export function getGlobalStateSize(): number {
  return 112;
}
