/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { getKeyDecoder, getKeyEncoder, type Key, type KeyArgs } from "../types";

export type InboundOrder = {
  key: Key;
  networkIn: number;
  nonce: ReadonlyUint8Array;
  bump: number;
};

export type InboundOrderArgs = {
  key: KeyArgs;
  networkIn: number;
  nonce: ReadonlyUint8Array;
  bump: number;
};

/** Gets the encoder for {@link InboundOrderArgs} account data. */
export function getInboundOrderEncoder(): FixedSizeEncoder<InboundOrderArgs> {
  return getStructEncoder([
    ["key", getKeyEncoder()],
    ["networkIn", getU32Encoder()],
    ["nonce", fixEncoderSize(getBytesEncoder(), 32)],
    ["bump", getU8Encoder()],
  ]);
}

/** Gets the decoder for {@link InboundOrder} account data. */
export function getInboundOrderDecoder(): FixedSizeDecoder<InboundOrder> {
  return getStructDecoder([
    ["key", getKeyDecoder()],
    ["networkIn", getU32Decoder()],
    ["nonce", fixDecoderSize(getBytesDecoder(), 32)],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link InboundOrder} account data. */
export function getInboundOrderCodec(): FixedSizeCodec<
  InboundOrderArgs,
  InboundOrder
> {
  return combineCodec(getInboundOrderEncoder(), getInboundOrderDecoder());
}

export function decodeInboundOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<InboundOrder, TAddress>;
export function decodeInboundOrder<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<InboundOrder, TAddress>;
export function decodeInboundOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<InboundOrder, TAddress> | MaybeAccount<InboundOrder, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getInboundOrderDecoder(),
  );
}

export async function fetchInboundOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<InboundOrder, TAddress>> {
  const maybeAccount = await fetchMaybeInboundOrder(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeInboundOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<InboundOrder, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeInboundOrder(maybeAccount);
}

export async function fetchAllInboundOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<InboundOrder>[]> {
  const maybeAccounts = await fetchAllMaybeInboundOrder(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeInboundOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<InboundOrder>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeInboundOrder(maybeAccount));
}

export function getInboundOrderSize(): number {
  return 38;
}
