/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { getKeyDecoder, getKeyEncoder, type Key, type KeyArgs } from "../types";

export type OutboundOrder = {
  key: Key;
  networkIn: number;
  networkOut: number;
  tokenIn: ReadonlyUint8Array;
  tokenOut: ReadonlyUint8Array;
  fromAddress: ReadonlyUint8Array;
  toAddress: ReadonlyUint8Array;
  amount: bigint;
  relayerFee: bigint;
  nonce: ReadonlyUint8Array;
  bump: number;
};

export type OutboundOrderArgs = {
  key: KeyArgs;
  networkIn: number;
  networkOut: number;
  tokenIn: ReadonlyUint8Array;
  tokenOut: ReadonlyUint8Array;
  fromAddress: ReadonlyUint8Array;
  toAddress: ReadonlyUint8Array;
  amount: number | bigint;
  relayerFee: number | bigint;
  nonce: ReadonlyUint8Array;
  bump: number;
};

/** Gets the encoder for {@link OutboundOrderArgs} account data. */
export function getOutboundOrderEncoder(): FixedSizeEncoder<OutboundOrderArgs> {
  return getStructEncoder([
    ["key", getKeyEncoder()],
    ["networkIn", getU32Encoder()],
    ["networkOut", getU32Encoder()],
    ["tokenIn", fixEncoderSize(getBytesEncoder(), 32)],
    ["tokenOut", fixEncoderSize(getBytesEncoder(), 32)],
    ["fromAddress", fixEncoderSize(getBytesEncoder(), 32)],
    ["toAddress", fixEncoderSize(getBytesEncoder(), 32)],
    ["amount", getU64Encoder()],
    ["relayerFee", getU64Encoder()],
    ["nonce", fixEncoderSize(getBytesEncoder(), 32)],
    ["bump", getU8Encoder()],
  ]);
}

/** Gets the decoder for {@link OutboundOrder} account data. */
export function getOutboundOrderDecoder(): FixedSizeDecoder<OutboundOrder> {
  return getStructDecoder([
    ["key", getKeyDecoder()],
    ["networkIn", getU32Decoder()],
    ["networkOut", getU32Decoder()],
    ["tokenIn", fixDecoderSize(getBytesDecoder(), 32)],
    ["tokenOut", fixDecoderSize(getBytesDecoder(), 32)],
    ["fromAddress", fixDecoderSize(getBytesDecoder(), 32)],
    ["toAddress", fixDecoderSize(getBytesDecoder(), 32)],
    ["amount", getU64Decoder()],
    ["relayerFee", getU64Decoder()],
    ["nonce", fixDecoderSize(getBytesDecoder(), 32)],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link OutboundOrder} account data. */
export function getOutboundOrderCodec(): FixedSizeCodec<
  OutboundOrderArgs,
  OutboundOrder
> {
  return combineCodec(getOutboundOrderEncoder(), getOutboundOrderDecoder());
}

export function decodeOutboundOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<OutboundOrder, TAddress>;
export function decodeOutboundOrder<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<OutboundOrder, TAddress>;
export function decodeOutboundOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<OutboundOrder, TAddress> | MaybeAccount<OutboundOrder, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOutboundOrderDecoder(),
  );
}

export async function fetchOutboundOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<OutboundOrder, TAddress>> {
  const maybeAccount = await fetchMaybeOutboundOrder(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOutboundOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<OutboundOrder, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOutboundOrder(maybeAccount);
}

export async function fetchAllOutboundOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<OutboundOrder>[]> {
  const maybeAccounts = await fetchAllMaybeOutboundOrder(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOutboundOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<OutboundOrder>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeOutboundOrder(maybeAccount));
}

export function getOutboundOrderSize(): number {
  return 186;
}
