/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from "@solana/kit";
import { getKeyDecoder, getKeyEncoder, type Key, type KeyArgs } from "../types";

export type Pauser = { key: Key; pauserPubkey: Address; bump: number };

export type PauserArgs = { key: KeyArgs; pauserPubkey: Address; bump: number };

/** Gets the encoder for {@link PauserArgs} account data. */
export function getPauserEncoder(): FixedSizeEncoder<PauserArgs> {
  return getStructEncoder([
    ["key", getKeyEncoder()],
    ["pauserPubkey", getAddressEncoder()],
    ["bump", getU8Encoder()],
  ]);
}

/** Gets the decoder for {@link Pauser} account data. */
export function getPauserDecoder(): FixedSizeDecoder<Pauser> {
  return getStructDecoder([
    ["key", getKeyDecoder()],
    ["pauserPubkey", getAddressDecoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Pauser} account data. */
export function getPauserCodec(): FixedSizeCodec<PauserArgs, Pauser> {
  return combineCodec(getPauserEncoder(), getPauserDecoder());
}

export function decodePauser<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Pauser, TAddress>;
export function decodePauser<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Pauser, TAddress>;
export function decodePauser<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Pauser, TAddress> | MaybeAccount<Pauser, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPauserDecoder(),
  );
}

export async function fetchPauser<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Pauser, TAddress>> {
  const maybeAccount = await fetchMaybePauser(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePauser<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Pauser, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePauser(maybeAccount);
}

export async function fetchAllPauser(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Pauser>[]> {
  const maybeAccounts = await fetchAllMaybePauser(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePauser(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Pauser>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodePauser(maybeAccount));
}

export function getPauserSize(): number {
  return 34;
}
