/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type Domain = {
  protocolName: string;
  protocolVersion: string;
  destinationChainId: number;
  contractAddress: ReadonlyUint8Array;
};

export type DomainArgs = Domain;

export function getDomainEncoder(): Encoder<DomainArgs> {
  return getStructEncoder([
    ["protocolName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    [
      "protocolVersion",
      addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
    ],
    ["destinationChainId", getU32Encoder()],
    ["contractAddress", fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getDomainDecoder(): Decoder<Domain> {
  return getStructDecoder([
    ["protocolName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    [
      "protocolVersion",
      addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder()),
    ],
    ["destinationChainId", getU32Decoder()],
    ["contractAddress", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getDomainCodec(): Codec<DomainArgs, Domain> {
  return combineCodec(getDomainEncoder(), getDomainDecoder());
}
