/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const ACCEPT_ADMIN_DISCRIMINATOR = 11;

export function getAcceptAdminDiscriminatorBytes() {
  return getU8Encoder().encode(ACCEPT_ADMIN_DISCRIMINATOR);
}

export type AcceptAdminInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountPendingAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPendingAdmin extends string
        ? WritableSignerAccount<TAccountPendingAdmin> &
            AccountSignerMeta<TAccountPendingAdmin>
        : TAccountPendingAdmin,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      ...TRemainingAccounts,
    ]
  >;

export type AcceptAdminInstructionData = { discriminator: number };

export type AcceptAdminInstructionDataArgs = {};

export function getAcceptAdminInstructionDataEncoder(): FixedSizeEncoder<AcceptAdminInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: ACCEPT_ADMIN_DISCRIMINATOR }),
  );
}

export function getAcceptAdminInstructionDataDecoder(): FixedSizeDecoder<AcceptAdminInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getAcceptAdminInstructionDataCodec(): FixedSizeCodec<
  AcceptAdminInstructionDataArgs,
  AcceptAdminInstructionData
> {
  return combineCodec(
    getAcceptAdminInstructionDataEncoder(),
    getAcceptAdminInstructionDataDecoder(),
  );
}

export type AcceptAdminInput<
  TAccountPendingAdmin extends string = string,
  TAccountGlobalState extends string = string,
> = {
  /** Pending admin accepting the transfer */
  pendingAdmin: TransactionSigner<TAccountPendingAdmin>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
};

export function getAcceptAdminInstruction<
  TAccountPendingAdmin extends string,
  TAccountGlobalState extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: AcceptAdminInput<TAccountPendingAdmin, TAccountGlobalState>,
  config?: { programAddress?: TProgramAddress },
): AcceptAdminInstruction<
  TProgramAddress,
  TAccountPendingAdmin,
  TAccountGlobalState
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    pendingAdmin: { value: input.pendingAdmin ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.pendingAdmin),
      getAccountMeta(accounts.globalState),
    ],
    data: getAcceptAdminInstructionDataEncoder().encode({}),
    programAddress,
  } as AcceptAdminInstruction<
    TProgramAddress,
    TAccountPendingAdmin,
    TAccountGlobalState
  >);
}

export type ParsedAcceptAdminInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Pending admin accepting the transfer */
    pendingAdmin: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
  };
  data: AcceptAdminInstructionData;
};

export function parseAcceptAdminInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAcceptAdminInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { pendingAdmin: getNextAccount(), globalState: getNextAccount() },
    data: getAcceptAdminInstructionDataDecoder().decode(instruction.data),
  };
}
