/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const ADD_ORACLE_DISCRIMINATOR = 7;

export function getAddOracleDiscriminatorBytes() {
  return getU8Encoder().encode(ADD_ORACLE_DISCRIMINATOR);
}

export type AddOracleInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountOraclePda extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountOraclePda extends string
        ? WritableAccount<TAccountOraclePda>
        : TAccountOraclePda,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AddOracleInstructionData = {
  discriminator: number;
  oraclePubkey: Address;
};

export type AddOracleInstructionDataArgs = { oraclePubkey: Address };

export function getAddOracleInstructionDataEncoder(): FixedSizeEncoder<AddOracleInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["oraclePubkey", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_ORACLE_DISCRIMINATOR }),
  );
}

export function getAddOracleInstructionDataDecoder(): FixedSizeDecoder<AddOracleInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["oraclePubkey", getAddressDecoder()],
  ]);
}

export function getAddOracleInstructionDataCodec(): FixedSizeCodec<
  AddOracleInstructionDataArgs,
  AddOracleInstructionData
> {
  return combineCodec(
    getAddOracleInstructionDataEncoder(),
    getAddOracleInstructionDataDecoder(),
  );
}

export type AddOracleInput<
  TAccountAdmin extends string = string,
  TAccountGlobalState extends string = string,
  TAccountOraclePda extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Oracle PDA */
  oraclePda: Address<TAccountOraclePda>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
  oraclePubkey: AddOracleInstructionDataArgs["oraclePubkey"];
};

export function getAddOracleInstruction<
  TAccountAdmin extends string,
  TAccountGlobalState extends string,
  TAccountOraclePda extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: AddOracleInput<
    TAccountAdmin,
    TAccountGlobalState,
    TAccountOraclePda,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AddOracleInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountGlobalState,
  TAccountOraclePda,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: true },
    oraclePda: { value: input.oraclePda ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.oraclePda),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAddOracleInstructionDataEncoder().encode(
      args as AddOracleInstructionDataArgs,
    ),
    programAddress,
  } as AddOracleInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalState,
    TAccountOraclePda,
    TAccountSystemProgram
  >);
}

export type ParsedAddOracleInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin */
    admin: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Oracle PDA */
    oraclePda: TAccountMetas[2];
    /** System Program Account */
    systemProgram: TAccountMetas[3];
  };
  data: AddOracleInstructionData;
};

export function parseAddOracleInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddOracleInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      globalState: getNextAccount(),
      oraclePda: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAddOracleInstructionDataDecoder().decode(instruction.data),
  };
}
