/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const ADD_PAUSER_DISCRIMINATOR = 3;

export function getAddPauserDiscriminatorBytes() {
  return getU8Encoder().encode(ADD_PAUSER_DISCRIMINATOR);
}

export type AddPauserInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountPauserPda extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGlobalState extends string
        ? ReadonlyAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountPauserPda extends string
        ? WritableAccount<TAccountPauserPda>
        : TAccountPauserPda,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AddPauserInstructionData = {
  discriminator: number;
  pauserPubkey: Address;
};

export type AddPauserInstructionDataArgs = { pauserPubkey: Address };

export function getAddPauserInstructionDataEncoder(): FixedSizeEncoder<AddPauserInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["pauserPubkey", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_PAUSER_DISCRIMINATOR }),
  );
}

export function getAddPauserInstructionDataDecoder(): FixedSizeDecoder<AddPauserInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["pauserPubkey", getAddressDecoder()],
  ]);
}

export function getAddPauserInstructionDataCodec(): FixedSizeCodec<
  AddPauserInstructionDataArgs,
  AddPauserInstructionData
> {
  return combineCodec(
    getAddPauserInstructionDataEncoder(),
    getAddPauserInstructionDataDecoder(),
  );
}

export type AddPauserInput<
  TAccountAdmin extends string = string,
  TAccountGlobalState extends string = string,
  TAccountPauserPda extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Pauser PDA */
  pauserPda: Address<TAccountPauserPda>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
  pauserPubkey: AddPauserInstructionDataArgs["pauserPubkey"];
};

export function getAddPauserInstruction<
  TAccountAdmin extends string,
  TAccountGlobalState extends string,
  TAccountPauserPda extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: AddPauserInput<
    TAccountAdmin,
    TAccountGlobalState,
    TAccountPauserPda,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AddPauserInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountGlobalState,
  TAccountPauserPda,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: false },
    pauserPda: { value: input.pauserPda ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.pauserPda),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAddPauserInstructionDataEncoder().encode(
      args as AddPauserInstructionDataArgs,
    ),
    programAddress,
  } as AddPauserInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalState,
    TAccountPauserPda,
    TAccountSystemProgram
  >);
}

export type ParsedAddPauserInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin */
    admin: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Pauser PDA */
    pauserPda: TAccountMetas[2];
    /** System Program Account */
    systemProgram: TAccountMetas[3];
  };
  data: AddPauserInstructionData;
};

export function parseAddPauserInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddPauserInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      globalState: getNextAccount(),
      pauserPda: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAddPauserInstructionDataDecoder().decode(instruction.data),
  };
}
