/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CLAIM_PROTOCOL_FEE_DISCRIMINATOR = 10;

export function getClaimProtocolFeeDiscriminatorBytes() {
  return getU8Encoder().encode(CLAIM_PROTOCOL_FEE_DISCRIMINATOR);
}

export type ClaimProtocolFeeInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountProtocolFeeRecipient extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountProtocolFeeRecipientAta extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountProtocolFeeRecipient extends string
        ? WritableSignerAccount<TAccountProtocolFeeRecipient> &
            AccountSignerMeta<TAccountProtocolFeeRecipient>
        : TAccountProtocolFeeRecipient,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountTokenMint extends string
        ? WritableAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountProtocolFeeRecipientAta extends string
        ? WritableAccount<TAccountProtocolFeeRecipientAta>
        : TAccountProtocolFeeRecipientAta,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimProtocolFeeInstructionData = { discriminator: number };

export type ClaimProtocolFeeInstructionDataArgs = {};

export function getClaimProtocolFeeInstructionDataEncoder(): FixedSizeEncoder<ClaimProtocolFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: CLAIM_PROTOCOL_FEE_DISCRIMINATOR }),
  );
}

export function getClaimProtocolFeeInstructionDataDecoder(): FixedSizeDecoder<ClaimProtocolFeeInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getClaimProtocolFeeInstructionDataCodec(): FixedSizeCodec<
  ClaimProtocolFeeInstructionDataArgs,
  ClaimProtocolFeeInstructionData
> {
  return combineCodec(
    getClaimProtocolFeeInstructionDataEncoder(),
    getClaimProtocolFeeInstructionDataDecoder(),
  );
}

export type ClaimProtocolFeeInput<
  TAccountProtocolFeeRecipient extends string = string,
  TAccountGlobalState extends string = string,
  TAccountTokenMint extends string = string,
  TAccountProtocolFeeRecipientAta extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Protocol Fee Recipient */
  protocolFeeRecipient: TransactionSigner<TAccountProtocolFeeRecipient>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Token Mint */
  tokenMint: Address<TAccountTokenMint>;
  /** Protocol Fee Recipient Associated Token Account */
  protocolFeeRecipientAta: Address<TAccountProtocolFeeRecipientAta>;
  /** Token Program Account */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** Associated Token Program Account */
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getClaimProtocolFeeInstruction<
  TAccountProtocolFeeRecipient extends string,
  TAccountGlobalState extends string,
  TAccountTokenMint extends string,
  TAccountProtocolFeeRecipientAta extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: ClaimProtocolFeeInput<
    TAccountProtocolFeeRecipient,
    TAccountGlobalState,
    TAccountTokenMint,
    TAccountProtocolFeeRecipientAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimProtocolFeeInstruction<
  TProgramAddress,
  TAccountProtocolFeeRecipient,
  TAccountGlobalState,
  TAccountTokenMint,
  TAccountProtocolFeeRecipientAta,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    protocolFeeRecipient: {
      value: input.protocolFeeRecipient ?? null,
      isWritable: true,
    },
    globalState: { value: input.globalState ?? null, isWritable: true },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    protocolFeeRecipientAta: {
      value: input.protocolFeeRecipientAta ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.protocolFeeRecipient),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.protocolFeeRecipientAta),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimProtocolFeeInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimProtocolFeeInstruction<
    TProgramAddress,
    TAccountProtocolFeeRecipient,
    TAccountGlobalState,
    TAccountTokenMint,
    TAccountProtocolFeeRecipientAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedClaimProtocolFeeInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Protocol Fee Recipient */
    protocolFeeRecipient: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Token Mint */
    tokenMint: TAccountMetas[2];
    /** Protocol Fee Recipient Associated Token Account */
    protocolFeeRecipientAta: TAccountMetas[3];
    /** Token Program Account */
    tokenProgram: TAccountMetas[4];
    /** Associated Token Program Account */
    associatedTokenProgram: TAccountMetas[5];
    /** System Program Account */
    systemProgram: TAccountMetas[6];
  };
  data: ClaimProtocolFeeInstructionData;
};

export function parseClaimProtocolFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimProtocolFeeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      protocolFeeRecipient: getNextAccount(),
      globalState: getNextAccount(),
      tokenMint: getNextAccount(),
      protocolFeeRecipientAta: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getClaimProtocolFeeInstructionDataDecoder().decode(instruction.data),
  };
}
