/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CLAIM_ORACLE_FEE_DISCRIMINATOR = 11;

export function getClaimOracleFeeDiscriminatorBytes() {
  return getU8Encoder().encode(CLAIM_ORACLE_FEE_DISCRIMINATOR);
}

export type ClaimOracleFeeInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountClaimer extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountOraclePda extends string | AccountMeta<string> = string,
  TAccountOracleOwner extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountOracleAta extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountClaimer extends string
        ? WritableSignerAccount<TAccountClaimer> &
            AccountSignerMeta<TAccountClaimer>
        : TAccountClaimer,
      TAccountGlobalState extends string
        ? ReadonlyAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountOraclePda extends string
        ? WritableAccount<TAccountOraclePda>
        : TAccountOraclePda,
      TAccountOracleOwner extends string
        ? ReadonlyAccount<TAccountOracleOwner>
        : TAccountOracleOwner,
      TAccountTokenMint extends string
        ? WritableAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountOracleAta extends string
        ? WritableAccount<TAccountOracleAta>
        : TAccountOracleAta,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimOracleFeeInstructionData = { discriminator: number };

export type ClaimOracleFeeInstructionDataArgs = {};

export function getClaimOracleFeeInstructionDataEncoder(): FixedSizeEncoder<ClaimOracleFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: CLAIM_ORACLE_FEE_DISCRIMINATOR }),
  );
}

export function getClaimOracleFeeInstructionDataDecoder(): FixedSizeDecoder<ClaimOracleFeeInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getClaimOracleFeeInstructionDataCodec(): FixedSizeCodec<
  ClaimOracleFeeInstructionDataArgs,
  ClaimOracleFeeInstructionData
> {
  return combineCodec(
    getClaimOracleFeeInstructionDataEncoder(),
    getClaimOracleFeeInstructionDataDecoder(),
  );
}

export type ClaimOracleFeeInput<
  TAccountClaimer extends string = string,
  TAccountGlobalState extends string = string,
  TAccountOraclePda extends string = string,
  TAccountOracleOwner extends string = string,
  TAccountTokenMint extends string = string,
  TAccountOracleAta extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Claimer (Admin or Oracle User) */
  claimer: TransactionSigner<TAccountClaimer>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Oracle PDA */
  oraclePda: Address<TAccountOraclePda>;
  /** Oracle Owner */
  oracleOwner: Address<TAccountOracleOwner>;
  /** Token Mint */
  tokenMint: Address<TAccountTokenMint>;
  /** Oracle Associated Token Account */
  oracleAta: Address<TAccountOracleAta>;
  /** Token Program Account */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** Associated Token Program Account */
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getClaimOracleFeeInstruction<
  TAccountClaimer extends string,
  TAccountGlobalState extends string,
  TAccountOraclePda extends string,
  TAccountOracleOwner extends string,
  TAccountTokenMint extends string,
  TAccountOracleAta extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: ClaimOracleFeeInput<
    TAccountClaimer,
    TAccountGlobalState,
    TAccountOraclePda,
    TAccountOracleOwner,
    TAccountTokenMint,
    TAccountOracleAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimOracleFeeInstruction<
  TProgramAddress,
  TAccountClaimer,
  TAccountGlobalState,
  TAccountOraclePda,
  TAccountOracleOwner,
  TAccountTokenMint,
  TAccountOracleAta,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    claimer: { value: input.claimer ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: false },
    oraclePda: { value: input.oraclePda ?? null, isWritable: true },
    oracleOwner: { value: input.oracleOwner ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    oracleAta: { value: input.oracleAta ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.claimer),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.oraclePda),
      getAccountMeta(accounts.oracleOwner),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.oracleAta),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getClaimOracleFeeInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimOracleFeeInstruction<
    TProgramAddress,
    TAccountClaimer,
    TAccountGlobalState,
    TAccountOraclePda,
    TAccountOracleOwner,
    TAccountTokenMint,
    TAccountOracleAta,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedClaimOracleFeeInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Claimer (Admin or Oracle User) */
    claimer: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Oracle PDA */
    oraclePda: TAccountMetas[2];
    /** Oracle Owner */
    oracleOwner: TAccountMetas[3];
    /** Token Mint */
    tokenMint: TAccountMetas[4];
    /** Oracle Associated Token Account */
    oracleAta: TAccountMetas[5];
    /** Token Program Account */
    tokenProgram: TAccountMetas[6];
    /** Associated Token Program Account */
    associatedTokenProgram: TAccountMetas[7];
    /** System Program Account */
    systemProgram: TAccountMetas[8];
  };
  data: ClaimOracleFeeInstructionData;
};

export function parseClaimOracleFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimOracleFeeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      claimer: getNextAccount(),
      globalState: getNextAccount(),
      oraclePda: getNextAccount(),
      oracleOwner: getNextAccount(),
      tokenMint: getNextAccount(),
      oracleAta: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getClaimOracleFeeInstructionDataDecoder().decode(instruction.data),
  };
}
