/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INIT_GLOBAL_STATE_DISCRIMINATOR = 0;

export function getInitGlobalStateDiscriminatorBytes() {
  return getU8Encoder().encode(INIT_GLOBAL_STATE_DISCRIMINATOR);
}

export type InitGlobalStateInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountProtocolFeeRecipient extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountTokenMetadata extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountTokenMetadataProgram extends string | AccountMeta<string> =
    "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountProtocolFeeRecipient extends string
        ? ReadonlyAccount<TAccountProtocolFeeRecipient>
        : TAccountProtocolFeeRecipient,
      TAccountTokenMint extends string
        ? WritableSignerAccount<TAccountTokenMint> &
            AccountSignerMeta<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountTokenMetadata extends string
        ? WritableAccount<TAccountTokenMetadata>
        : TAccountTokenMetadata,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountTokenMetadataProgram extends string
        ? ReadonlyAccount<TAccountTokenMetadataProgram>
        : TAccountTokenMetadataProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitGlobalStateInstructionData = {
  discriminator: number;
  bpsFee: number;
  protocolFeeBpsOfBps: number;
  uri: string;
  name: string;
  symbol: string;
};

export type InitGlobalStateInstructionDataArgs = {
  bpsFee: number;
  protocolFeeBpsOfBps: number;
  uri: string;
  name: string;
  symbol: string;
};

export function getInitGlobalStateInstructionDataEncoder(): Encoder<InitGlobalStateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["bpsFee", getU16Encoder()],
      ["protocolFeeBpsOfBps", getU16Encoder()],
      ["uri", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["name", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["symbol", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: INIT_GLOBAL_STATE_DISCRIMINATOR }),
  );
}

export function getInitGlobalStateInstructionDataDecoder(): Decoder<InitGlobalStateInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["bpsFee", getU16Decoder()],
    ["protocolFeeBpsOfBps", getU16Decoder()],
    ["uri", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["name", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["symbol", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getInitGlobalStateInstructionDataCodec(): Codec<
  InitGlobalStateInstructionDataArgs,
  InitGlobalStateInstructionData
> {
  return combineCodec(
    getInitGlobalStateInstructionDataEncoder(),
    getInitGlobalStateInstructionDataDecoder(),
  );
}

export type InitGlobalStateInput<
  TAccountAdmin extends string = string,
  TAccountGlobalState extends string = string,
  TAccountProtocolFeeRecipient extends string = string,
  TAccountTokenMint extends string = string,
  TAccountTokenMetadata extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountTokenMetadataProgram extends string = string,
> = {
  /** Admin */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Protocol Fee Recipient */
  protocolFeeRecipient: Address<TAccountProtocolFeeRecipient>;
  /** Token Mint */
  tokenMint: TransactionSigner<TAccountTokenMint>;
  /** Token Metadata */
  tokenMetadata: Address<TAccountTokenMetadata>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
  /** Token Program Account */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** Token Metadata Program Account */
  tokenMetadataProgram?: Address<TAccountTokenMetadataProgram>;
  bpsFee: InitGlobalStateInstructionDataArgs["bpsFee"];
  protocolFeeBpsOfBps: InitGlobalStateInstructionDataArgs["protocolFeeBpsOfBps"];
  uri: InitGlobalStateInstructionDataArgs["uri"];
  name: InitGlobalStateInstructionDataArgs["name"];
  symbol: InitGlobalStateInstructionDataArgs["symbol"];
};

export function getInitGlobalStateInstruction<
  TAccountAdmin extends string,
  TAccountGlobalState extends string,
  TAccountProtocolFeeRecipient extends string,
  TAccountTokenMint extends string,
  TAccountTokenMetadata extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountTokenMetadataProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: InitGlobalStateInput<
    TAccountAdmin,
    TAccountGlobalState,
    TAccountProtocolFeeRecipient,
    TAccountTokenMint,
    TAccountTokenMetadata,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountTokenMetadataProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitGlobalStateInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountGlobalState,
  TAccountProtocolFeeRecipient,
  TAccountTokenMint,
  TAccountTokenMetadata,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountTokenMetadataProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: true },
    protocolFeeRecipient: {
      value: input.protocolFeeRecipient ?? null,
      isWritable: false,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    tokenMetadata: { value: input.tokenMetadata ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    tokenMetadataProgram: {
      value: input.tokenMetadataProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.tokenMetadataProgram.value) {
    accounts.tokenMetadataProgram.value =
      "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" as Address<"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.protocolFeeRecipient),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.tokenMetadata),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.tokenMetadataProgram),
    ],
    data: getInitGlobalStateInstructionDataEncoder().encode(
      args as InitGlobalStateInstructionDataArgs,
    ),
    programAddress,
  } as InitGlobalStateInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalState,
    TAccountProtocolFeeRecipient,
    TAccountTokenMint,
    TAccountTokenMetadata,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountTokenMetadataProgram
  >);
}

export type ParsedInitGlobalStateInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin */
    admin: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Protocol Fee Recipient */
    protocolFeeRecipient: TAccountMetas[2];
    /** Token Mint */
    tokenMint: TAccountMetas[3];
    /** Token Metadata */
    tokenMetadata: TAccountMetas[4];
    /** System Program Account */
    systemProgram: TAccountMetas[5];
    /** Token Program Account */
    tokenProgram: TAccountMetas[6];
    /** Token Metadata Program Account */
    tokenMetadataProgram: TAccountMetas[7];
  };
  data: InitGlobalStateInstructionData;
};

export function parseInitGlobalStateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitGlobalStateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      globalState: getNextAccount(),
      protocolFeeRecipient: getNextAccount(),
      tokenMint: getNextAccount(),
      tokenMetadata: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      tokenMetadataProgram: getNextAccount(),
    },
    data: getInitGlobalStateInstructionDataDecoder().decode(instruction.data),
  };
}
