/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INIT_GLOBAL_STATE_DISCRIMINATOR = 0;

export function getInitGlobalStateDiscriminatorBytes() {
  return getU8Encoder().encode(INIT_GLOBAL_STATE_DISCRIMINATOR);
}

export type InitGlobalStateInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountProtocolFeeRecipient extends string | AccountMeta<string> = string,
  TAccountOracleFeeRecipient extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountProtocolFeeRecipient extends string
        ? ReadonlyAccount<TAccountProtocolFeeRecipient>
        : TAccountProtocolFeeRecipient,
      TAccountOracleFeeRecipient extends string
        ? ReadonlyAccount<TAccountOracleFeeRecipient>
        : TAccountOracleFeeRecipient,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitGlobalStateInstructionData = {
  discriminator: number;
  bpsFee: number;
  protocolFeeBpsOfBps: number;
  oracleThresholdPercent: number;
};

export type InitGlobalStateInstructionDataArgs = {
  bpsFee: number;
  protocolFeeBpsOfBps: number;
  oracleThresholdPercent: number;
};

export function getInitGlobalStateInstructionDataEncoder(): FixedSizeEncoder<InitGlobalStateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["bpsFee", getU16Encoder()],
      ["protocolFeeBpsOfBps", getU16Encoder()],
      ["oracleThresholdPercent", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_GLOBAL_STATE_DISCRIMINATOR }),
  );
}

export function getInitGlobalStateInstructionDataDecoder(): FixedSizeDecoder<InitGlobalStateInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["bpsFee", getU16Decoder()],
    ["protocolFeeBpsOfBps", getU16Decoder()],
    ["oracleThresholdPercent", getU8Decoder()],
  ]);
}

export function getInitGlobalStateInstructionDataCodec(): FixedSizeCodec<
  InitGlobalStateInstructionDataArgs,
  InitGlobalStateInstructionData
> {
  return combineCodec(
    getInitGlobalStateInstructionDataEncoder(),
    getInitGlobalStateInstructionDataDecoder(),
  );
}

export type InitGlobalStateInput<
  TAccountAdmin extends string = string,
  TAccountGlobalState extends string = string,
  TAccountProtocolFeeRecipient extends string = string,
  TAccountOracleFeeRecipient extends string = string,
  TAccountTokenMint extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Protocol Fee Recipient */
  protocolFeeRecipient: Address<TAccountProtocolFeeRecipient>;
  /** Oracle Fee Recipient */
  oracleFeeRecipient: Address<TAccountOracleFeeRecipient>;
  /** Token Mint */
  tokenMint: Address<TAccountTokenMint>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
  bpsFee: InitGlobalStateInstructionDataArgs["bpsFee"];
  protocolFeeBpsOfBps: InitGlobalStateInstructionDataArgs["protocolFeeBpsOfBps"];
  oracleThresholdPercent: InitGlobalStateInstructionDataArgs["oracleThresholdPercent"];
};

export function getInitGlobalStateInstruction<
  TAccountAdmin extends string,
  TAccountGlobalState extends string,
  TAccountProtocolFeeRecipient extends string,
  TAccountOracleFeeRecipient extends string,
  TAccountTokenMint extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: InitGlobalStateInput<
    TAccountAdmin,
    TAccountGlobalState,
    TAccountProtocolFeeRecipient,
    TAccountOracleFeeRecipient,
    TAccountTokenMint,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitGlobalStateInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountGlobalState,
  TAccountProtocolFeeRecipient,
  TAccountOracleFeeRecipient,
  TAccountTokenMint,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: true },
    protocolFeeRecipient: {
      value: input.protocolFeeRecipient ?? null,
      isWritable: false,
    },
    oracleFeeRecipient: {
      value: input.oracleFeeRecipient ?? null,
      isWritable: false,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.protocolFeeRecipient),
      getAccountMeta(accounts.oracleFeeRecipient),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitGlobalStateInstructionDataEncoder().encode(
      args as InitGlobalStateInstructionDataArgs,
    ),
    programAddress,
  } as InitGlobalStateInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalState,
    TAccountProtocolFeeRecipient,
    TAccountOracleFeeRecipient,
    TAccountTokenMint,
    TAccountSystemProgram
  >);
}

export type ParsedInitGlobalStateInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin */
    admin: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Protocol Fee Recipient */
    protocolFeeRecipient: TAccountMetas[2];
    /** Oracle Fee Recipient */
    oracleFeeRecipient: TAccountMetas[3];
    /** Token Mint */
    tokenMint: TAccountMetas[4];
    /** System Program Account */
    systemProgram: TAccountMetas[5];
  };
  data: InitGlobalStateInstructionData;
};

export function parseInitGlobalStateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitGlobalStateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      globalState: getNextAccount(),
      protocolFeeRecipient: getNextAccount(),
      oracleFeeRecipient: getNextAccount(),
      tokenMint: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitGlobalStateInstructionDataDecoder().decode(instruction.data),
  };
}
