/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const OUTBOUND_DISCRIMINATOR = 1;

export function getOutboundDiscriminatorBytes() {
  return getU8Encoder().encode(OUTBOUND_DISCRIMINATOR);
}

export type OutboundInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountOutboundOrder extends string | AccountMeta<string> = string,
  TAccountUserTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountGlobalState extends string
        ? ReadonlyAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountOutboundOrder extends string
        ? WritableAccount<TAccountOutboundOrder>
        : TAccountOutboundOrder,
      TAccountUserTokenAccount extends string
        ? WritableAccount<TAccountUserTokenAccount>
        : TAccountUserTokenAccount,
      TAccountTokenMint extends string
        ? WritableAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type OutboundInstructionData = {
  discriminator: number;
  networkOut: number;
  tokenOut: ReadonlyUint8Array;
  toAddress: ReadonlyUint8Array;
  amount: bigint;
  relayerFee: bigint;
  nonce: ReadonlyUint8Array;
};

export type OutboundInstructionDataArgs = {
  networkOut: number;
  tokenOut: ReadonlyUint8Array;
  toAddress: ReadonlyUint8Array;
  amount: number | bigint;
  relayerFee: number | bigint;
  nonce: ReadonlyUint8Array;
};

export function getOutboundInstructionDataEncoder(): FixedSizeEncoder<OutboundInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["networkOut", getU32Encoder()],
      ["tokenOut", fixEncoderSize(getBytesEncoder(), 32)],
      ["toAddress", fixEncoderSize(getBytesEncoder(), 32)],
      ["amount", getU64Encoder()],
      ["relayerFee", getU64Encoder()],
      ["nonce", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: OUTBOUND_DISCRIMINATOR }),
  );
}

export function getOutboundInstructionDataDecoder(): FixedSizeDecoder<OutboundInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["networkOut", getU32Decoder()],
    ["tokenOut", fixDecoderSize(getBytesDecoder(), 32)],
    ["toAddress", fixDecoderSize(getBytesDecoder(), 32)],
    ["amount", getU64Decoder()],
    ["relayerFee", getU64Decoder()],
    ["nonce", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getOutboundInstructionDataCodec(): FixedSizeCodec<
  OutboundInstructionDataArgs,
  OutboundInstructionData
> {
  return combineCodec(
    getOutboundInstructionDataEncoder(),
    getOutboundInstructionDataDecoder(),
  );
}

export type OutboundInput<
  TAccountUser extends string = string,
  TAccountGlobalState extends string = string,
  TAccountOutboundOrder extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** User who is locking tokens */
  user: TransactionSigner<TAccountUser>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Outbound Order PDA */
  outboundOrder: Address<TAccountOutboundOrder>;
  /** User's token account to burn from */
  userTokenAccount: Address<TAccountUserTokenAccount>;
  /** Token Mint */
  tokenMint: Address<TAccountTokenMint>;
  /** Token Program Account */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program Account */
  systemProgram?: Address<TAccountSystemProgram>;
  networkOut: OutboundInstructionDataArgs["networkOut"];
  tokenOut: OutboundInstructionDataArgs["tokenOut"];
  toAddress: OutboundInstructionDataArgs["toAddress"];
  amount: OutboundInstructionDataArgs["amount"];
  relayerFee: OutboundInstructionDataArgs["relayerFee"];
  nonce: OutboundInstructionDataArgs["nonce"];
};

export function getOutboundInstruction<
  TAccountUser extends string,
  TAccountGlobalState extends string,
  TAccountOutboundOrder extends string,
  TAccountUserTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: OutboundInput<
    TAccountUser,
    TAccountGlobalState,
    TAccountOutboundOrder,
    TAccountUserTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): OutboundInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountGlobalState,
  TAccountOutboundOrder,
  TAccountUserTokenAccount,
  TAccountTokenMint,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: false },
    outboundOrder: { value: input.outboundOrder ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.outboundOrder),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getOutboundInstructionDataEncoder().encode(
      args as OutboundInstructionDataArgs,
    ),
    programAddress,
  } as OutboundInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGlobalState,
    TAccountOutboundOrder,
    TAccountUserTokenAccount,
    TAccountTokenMint,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedOutboundInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** User who is locking tokens */
    user: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Outbound Order PDA */
    outboundOrder: TAccountMetas[2];
    /** User's token account to burn from */
    userTokenAccount: TAccountMetas[3];
    /** Token Mint */
    tokenMint: TAccountMetas[4];
    /** Token Program Account */
    tokenProgram: TAccountMetas[5];
    /** System Program Account */
    systemProgram: TAccountMetas[6];
  };
  data: OutboundInstructionData;
};

export function parseOutboundInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedOutboundInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      globalState: getNextAccount(),
      outboundOrder: getNextAccount(),
      userTokenAccount: getNextAccount(),
      tokenMint: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getOutboundInstructionDataDecoder().decode(instruction.data),
  };
}
