/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const TRANSFER_ADMIN_DISCRIMINATOR = 10;

export function getTransferAdminDiscriminatorBytes() {
  return getU8Encoder().encode(TRANSFER_ADMIN_DISCRIMINATOR);
}

export type TransferAdminInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      ...TRemainingAccounts,
    ]
  >;

export type TransferAdminInstructionData = {
  discriminator: number;
  newAdmin: Address;
};

export type TransferAdminInstructionDataArgs = { newAdmin: Address };

export function getTransferAdminInstructionDataEncoder(): FixedSizeEncoder<TransferAdminInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["newAdmin", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_ADMIN_DISCRIMINATOR }),
  );
}

export function getTransferAdminInstructionDataDecoder(): FixedSizeDecoder<TransferAdminInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["newAdmin", getAddressDecoder()],
  ]);
}

export function getTransferAdminInstructionDataCodec(): FixedSizeCodec<
  TransferAdminInstructionDataArgs,
  TransferAdminInstructionData
> {
  return combineCodec(
    getTransferAdminInstructionDataEncoder(),
    getTransferAdminInstructionDataDecoder(),
  );
}

export type TransferAdminInput<
  TAccountAdmin extends string = string,
  TAccountGlobalState extends string = string,
> = {
  /** Current admin */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  newAdmin: TransferAdminInstructionDataArgs["newAdmin"];
};

export function getTransferAdminInstruction<
  TAccountAdmin extends string,
  TAccountGlobalState extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: TransferAdminInput<TAccountAdmin, TAccountGlobalState>,
  config?: { programAddress?: TProgramAddress },
): TransferAdminInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountGlobalState
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.globalState),
    ],
    data: getTransferAdminInstructionDataEncoder().encode(
      args as TransferAdminInstructionDataArgs,
    ),
    programAddress,
  } as TransferAdminInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalState
  >);
}

export type ParsedTransferAdminInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Current admin */
    admin: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
  };
  data: TransferAdminInstructionData;
};

export function parseTransferAdminInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferAdminInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), globalState: getNextAccount() },
    data: getTransferAdminInstructionDataDecoder().decode(instruction.data),
  };
}
