/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const UNPAUSE_DISCRIMINATOR = 6;

export function getUnpauseDiscriminatorBytes() {
  return getU8Encoder().encode(UNPAUSE_DISCRIMINATOR);
}

export type UnpauseInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountPauser extends string | AccountMeta<string> = string,
  TAccountGlobalState extends string | AccountMeta<string> = string,
  TAccountPauserPda extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPauser extends string
        ? WritableSignerAccount<TAccountPauser> &
            AccountSignerMeta<TAccountPauser>
        : TAccountPauser,
      TAccountGlobalState extends string
        ? WritableAccount<TAccountGlobalState>
        : TAccountGlobalState,
      TAccountPauserPda extends string
        ? ReadonlyAccount<TAccountPauserPda>
        : TAccountPauserPda,
      ...TRemainingAccounts,
    ]
  >;

export type UnpauseInstructionData = { discriminator: number };

export type UnpauseInstructionDataArgs = {};

export function getUnpauseInstructionDataEncoder(): FixedSizeEncoder<UnpauseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: UNPAUSE_DISCRIMINATOR }),
  );
}

export function getUnpauseInstructionDataDecoder(): FixedSizeDecoder<UnpauseInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getUnpauseInstructionDataCodec(): FixedSizeCodec<
  UnpauseInstructionDataArgs,
  UnpauseInstructionData
> {
  return combineCodec(
    getUnpauseInstructionDataEncoder(),
    getUnpauseInstructionDataDecoder(),
  );
}

export type UnpauseInput<
  TAccountPauser extends string = string,
  TAccountGlobalState extends string = string,
  TAccountPauserPda extends string = string,
> = {
  /** Pauser */
  pauser: TransactionSigner<TAccountPauser>;
  /** Global State */
  globalState: Address<TAccountGlobalState>;
  /** Pauser PDA */
  pauserPda: Address<TAccountPauserPda>;
};

export function getUnpauseInstruction<
  TAccountPauser extends string,
  TAccountGlobalState extends string,
  TAccountPauserPda extends string,
  TProgramAddress extends Address = typeof QS_BRIDGE_PROGRAM_ADDRESS,
>(
  input: UnpauseInput<TAccountPauser, TAccountGlobalState, TAccountPauserPda>,
  config?: { programAddress?: TProgramAddress },
): UnpauseInstruction<
  TProgramAddress,
  TAccountPauser,
  TAccountGlobalState,
  TAccountPauserPda
> {
  // Program address.
  const programAddress = config?.programAddress ?? QS_BRIDGE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    pauser: { value: input.pauser ?? null, isWritable: true },
    globalState: { value: input.globalState ?? null, isWritable: true },
    pauserPda: { value: input.pauserPda ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.pauser),
      getAccountMeta(accounts.globalState),
      getAccountMeta(accounts.pauserPda),
    ],
    data: getUnpauseInstructionDataEncoder().encode({}),
    programAddress,
  } as UnpauseInstruction<
    TProgramAddress,
    TAccountPauser,
    TAccountGlobalState,
    TAccountPauserPda
  >);
}

export type ParsedUnpauseInstruction<
  TProgram extends string = typeof QS_BRIDGE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Pauser */
    pauser: TAccountMetas[0];
    /** Global State */
    globalState: TAccountMetas[1];
    /** Pauser PDA */
    pauserPda: TAccountMetas[2];
  };
  data: UnpauseInstructionData;
};

export function parseUnpauseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUnpauseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      pauser: getNextAccount(),
      globalState: getNextAccount(),
      pauserPda: getNextAccount(),
    },
    data: getUnpauseInstructionDataDecoder().decode(instruction.data),
  };
}
