/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedAddOracleInstruction,
  type ParsedAddPauserInstruction,
  type ParsedClaimOracleFeeInstruction,
  type ParsedClaimProtocolFeeInstruction,
  type ParsedInboundInstruction,
  type ParsedInitGlobalStateInstruction,
  type ParsedOutboundInstruction,
  type ParsedOverrideOutboundInstruction,
  type ParsedPauseInstruction,
  type ParsedRemoveOracleInstruction,
  type ParsedRemovePauserInstruction,
  type ParsedUnpauseInstruction,
} from "../instructions";

export const QS_BRIDGE_PROGRAM_ADDRESS =
  "qSBGtee9tspoDVmb867Wq6tcR3kp19XN1PbBVckrH7H" as Address<"qSBGtee9tspoDVmb867Wq6tcR3kp19XN1PbBVckrH7H">;

export enum QsBridgeAccount {
  GlobalState,
  InboundOrder,
  Oracle,
  OutboundOrder,
  Pauser,
}

export enum QsBridgeInstruction {
  InitGlobalState,
  Outbound,
  OverrideOutbound,
  AddPauser,
  RemovePauser,
  Pause,
  Unpause,
  AddOracle,
  RemoveOracle,
  Inbound,
  ClaimProtocolFee,
  ClaimOracleFee,
}

export function identifyQsBridgeInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): QsBridgeInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return QsBridgeInstruction.InitGlobalState;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return QsBridgeInstruction.Outbound;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return QsBridgeInstruction.OverrideOutbound;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return QsBridgeInstruction.AddPauser;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return QsBridgeInstruction.RemovePauser;
  }
  if (containsBytes(data, getU8Encoder().encode(5), 0)) {
    return QsBridgeInstruction.Pause;
  }
  if (containsBytes(data, getU8Encoder().encode(6), 0)) {
    return QsBridgeInstruction.Unpause;
  }
  if (containsBytes(data, getU8Encoder().encode(7), 0)) {
    return QsBridgeInstruction.AddOracle;
  }
  if (containsBytes(data, getU8Encoder().encode(8), 0)) {
    return QsBridgeInstruction.RemoveOracle;
  }
  if (containsBytes(data, getU8Encoder().encode(9), 0)) {
    return QsBridgeInstruction.Inbound;
  }
  if (containsBytes(data, getU8Encoder().encode(10), 0)) {
    return QsBridgeInstruction.ClaimProtocolFee;
  }
  if (containsBytes(data, getU8Encoder().encode(11), 0)) {
    return QsBridgeInstruction.ClaimOracleFee;
  }
  throw new Error(
    "The provided instruction could not be identified as a qsBridge instruction.",
  );
}

export type ParsedQsBridgeInstruction<
  TProgram extends string = "qSBGtee9tspoDVmb867Wq6tcR3kp19XN1PbBVckrH7H",
> =
  | ({
      instructionType: QsBridgeInstruction.InitGlobalState;
    } & ParsedInitGlobalStateInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.Outbound;
    } & ParsedOutboundInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.OverrideOutbound;
    } & ParsedOverrideOutboundInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.AddPauser;
    } & ParsedAddPauserInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.RemovePauser;
    } & ParsedRemovePauserInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.Pause;
    } & ParsedPauseInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.Unpause;
    } & ParsedUnpauseInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.AddOracle;
    } & ParsedAddOracleInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.RemoveOracle;
    } & ParsedRemoveOracleInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.Inbound;
    } & ParsedInboundInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.ClaimProtocolFee;
    } & ParsedClaimProtocolFeeInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.ClaimOracleFee;
    } & ParsedClaimOracleFeeInstruction<TProgram>);
