/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedInitGlobalStateInstruction,
  type ParsedOutboundInstruction,
} from "../instructions";

export const QS_BRIDGE_PROGRAM_ADDRESS =
  "qSBGtee9tspoDVmb867Wq6tcR3kp19XN1PbBVckrH7H" as Address<"qSBGtee9tspoDVmb867Wq6tcR3kp19XN1PbBVckrH7H">;

export enum QsBridgeAccount {
  GlobalState,
  InboundOrder,
  Oracle,
  OutboundOrder,
  Pauser,
}

export enum QsBridgeInstruction {
  InitGlobalState,
  Outbound,
}

export function identifyQsBridgeInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): QsBridgeInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return QsBridgeInstruction.InitGlobalState;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return QsBridgeInstruction.Outbound;
  }
  throw new Error(
    "The provided instruction could not be identified as a qsBridge instruction.",
  );
}

export type ParsedQsBridgeInstruction<
  TProgram extends string = "qSBGtee9tspoDVmb867Wq6tcR3kp19XN1PbBVckrH7H",
> =
  | ({
      instructionType: QsBridgeInstruction.InitGlobalState;
    } & ParsedInitGlobalStateInstruction<TProgram>)
  | ({
      instructionType: QsBridgeInstruction.Outbound;
    } & ParsedOutboundInstruction<TProgram>);
