/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  getU32Encoder,
  getUtf8Encoder,
  type Address,
  type ProgramDerivedAddress,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type OutboundOrderSeeds = {
  networkOut: number;
  nonce: ReadonlyUint8Array;
};

export async function findOutboundOrderPda(
  seeds: OutboundOrderSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "9HzXq7P6UEQjJCrvbPCt4eZRvkoJU9jo1mSssbMHkncQ" as Address<"9HzXq7P6UEQjJCrvbPCt4eZRvkoJU9jo1mSssbMHkncQ">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getUtf8Encoder().encode("outbound_order"),
      getU32Encoder().encode(seeds.networkOut),
      getBytesEncoder().encode(seeds.nonce),
    ],
  });
}
