/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { QS_BRIDGE_PROGRAM_ADDRESS } from "../programs";

/** ProgramPaused: Program is paused */
export const QS_BRIDGE_ERROR__PROGRAM_PAUSED = 0x0; // 0
/** UnsupportedNetwork: Unsupported network */
export const QS_BRIDGE_ERROR__UNSUPPORTED_NETWORK = 0x1; // 1
/** UnsupportedOutToken: Unsupported out token */
export const QS_BRIDGE_ERROR__UNSUPPORTED_OUT_TOKEN = 0x2; // 2
/** OracleHasClaimableBalance: Oracle has claimable balance */
export const QS_BRIDGE_ERROR__ORACLE_HAS_CLAIMABLE_BALANCE = 0x3; // 3
/** InvalidNumberOfSignatures: Invalid number of signatures */
export const QS_BRIDGE_ERROR__INVALID_NUMBER_OF_SIGNATURES = 0x4; // 4

export type QsBridgeError =
  | typeof QS_BRIDGE_ERROR__INVALID_NUMBER_OF_SIGNATURES
  | typeof QS_BRIDGE_ERROR__ORACLE_HAS_CLAIMABLE_BALANCE
  | typeof QS_BRIDGE_ERROR__PROGRAM_PAUSED
  | typeof QS_BRIDGE_ERROR__UNSUPPORTED_NETWORK
  | typeof QS_BRIDGE_ERROR__UNSUPPORTED_OUT_TOKEN;

let qsBridgeErrorMessages: Record<QsBridgeError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  qsBridgeErrorMessages = {
    [QS_BRIDGE_ERROR__INVALID_NUMBER_OF_SIGNATURES]: `Invalid number of signatures`,
    [QS_BRIDGE_ERROR__ORACLE_HAS_CLAIMABLE_BALANCE]: `Oracle has claimable balance`,
    [QS_BRIDGE_ERROR__PROGRAM_PAUSED]: `Program is paused`,
    [QS_BRIDGE_ERROR__UNSUPPORTED_NETWORK]: `Unsupported network`,
    [QS_BRIDGE_ERROR__UNSUPPORTED_OUT_TOKEN]: `Unsupported out token`,
  };
}

export function getQsBridgeErrorMessage(code: QsBridgeError): string {
  if (process.env.NODE_ENV !== "production") {
    return (qsBridgeErrorMessages as Record<QsBridgeError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isQsBridgeError<TProgramErrorCode extends QsBridgeError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    QS_BRIDGE_PROGRAM_ADDRESS,
    code,
  );
}
